language: php
php:
  - 5.6
env:
  - DIR=plugins/domoticz
  - DIR=plugins/kodi
  - DIR=plugins/marantz
  - DIR=plugins/transmission
install: cd $DIR && composer install
script: phpunit --coverage-clover=coverage.clover
after_script:
  - zip -r domoticz.zip plugins/domoticz
  - zip -r kodi.zip plugins/kodi
  - zip -r marantz.zip plugins/marantz
  - zip -r transmission.zip plugins/transmission
